### ISSUE TITLE
URL Excludelist

### ISSUE THREAD

**Issue by stackpivot** [343max/TabHibernation#10]
add a configurable list of pages, that are not send to sleep when sleep-button is pushed.
This would be interesting for sites with dynamic Contant (Chats, Socialnetworks.)

**Comment by moritzadler** [comment]
Propose to merge with this issue (whitelist URLs from sending to sleep): https://github.com/343max/TabHibernation/issues/2

**Comment by HorayNarea** [comment]
@moritzadler is right
duplicate of #2
