### ISSUE TITLE
Questions about restoring many tabs

### ISSUE THREAD

**Issue by niutech** [343max/TabHibernation#15]
I have a couple of Chrome windows with a lot of tabs in each of them and I don't want to lose them. So before I install your extension, I would like to ask you some questions:
1. Will all tabs in all windows be hibernated after installing it?
2. What if Chrome suddenly crashes with my tabs hibernated? Will they be restored on the next start?
Thanks!

**Comment by 343max** [comment]
Maybe you should try outIt would be nice if you could test this with a different Chrome instance and tell me the results.
