### ISSUE TITLE
Selecting multiple tabs not to hibernate

### ISSUE THREAD

**Issue by mxmilkiib** [343max/TabHibernation#16]
In Chrome one can ctrl+click and shift+click to select multiple tabs. It would be neat if, when multiple tabs are selected, that Tab Hibernation avoids hibernating these tabs.

**Comment by 343max** [comment]
Hey! Didn't know you can do this and it seems to be only possible on Windows. I'll keep this open as an idea but chances I will implemented are quite low currently as I'm not currently using this Extension by myself anymore.

**Comment by HorayNarea** [comment]
Ctrl+Click works in Chrome on Linux too
